<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>3535fe73-44e7-4cd8-a5d2-d127fa502dc5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.5" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.7.0" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="4.6.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="14.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\swagger.json" Namespace="ApplicationTracker.ApiClient" ClassName="ApplicationTrackerApiClient">
      <SourceUri>http://localhost:8160/swagger/v1/swagger.json</SourceUri>
    </OpenApiReference>
  </ItemGroup>

</Project>
